--Step 1: Use the database “SQL_Course” (created in previous self evaluation)
--Step 2: Create a table called “SQL_CourseTable”
--Step 3: This table will have 4 columns – “ID, Name, Address, Visits”
		--DataTypes
			--ID – varchar(50)
			--Name – varchar(255)
			--Address – varchar(255)
			--Visits - int
--Step 4: Make ID a primary key
--Step 5: ID cannot have null values
--Step 6: If “Visits” has a null value then set default value to “0”
--Step 7: Insert 5 rows of data (make up your own data)